# The "Clean And Simple" (CAS) software framework, tools, and documentation
# are distributed under the terms of the MIT license a copy of which is
# included with this package (see the file "LICENSE" in the CAS poject tree's
# root directory).  CAS may be used for any purpose, including commercial
# purposes, at absolutely no cost. No paperwork, no royalties, no GNU-like
# "copyleft" restrictions, either.  Just download it and use it.
# 
# Copyright (c) 2016 Randall Lee White

TGT := casTest
SRCS := \
 casTest.cpp \
 basicTests.cpp \
 basicTestTests.cpp \
 testCase.cpp \
 testRunner.cpp \
 testRunnerTests.cpp

INCLUDES := 

#Compile flags.
CFLAGS := -fpic

#Link flags.
LFLAGS :=

#Paths to libraries.
LPATHS :=

#Libraries target is to be linked to.
LIBS :=

#Addition target dependencies.
TDEPS :=

include $(CAS_DIR)/rules.make/makefile.exec
